import {StyleSheet} from 'react-native';
export default StyleSheet.create({
  cardViewContainer: {
    padding: 10,
    height: 45,
    justifyContent: 'space-between',
    alignContent: 'center',
    elevation: 6,
    borderRadius: 10,
    shadowOffset: {width: 0, height: 2},
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#8408B5',
    flexDirection: 'row',
  },
  cardContainer: {
    padding: 10,
    height: 45,
    justifyContent: 'space-between',
    alignContent: 'center',
    elevation: 6,
    borderRadius: 10,
    shadowOffset: {width: 0, height: 2},
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#04CEB2',
    flexDirection: 'row',
  },
  container: {
    padding: 10,
    height: 45,
    justifyContent: 'space-between',
    alignContent: 'center',
    elevation: 6,
    borderRadius: 10,
    shadowOffset: {width: 0, height: 2},
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: '#C61818',
    flexDirection: 'row',
  },
  c: {
    padding: 10,
    height: 75,
    justifyContent: 'space-between',
    alignContent: 'center',
    elevation: 6,
    borderRadius: 10,
    shadowOffset: {width: 0, height: 2},
    backgroundColor: 'white',
    borderWidth: 1,
    borderColor: 'lightgray',
    flexDirection: 'row',
  },
  hScreenImage: {
    margin: 20,
    width: 65,
    height: 60,
  },
  textContainer: {
    paddingTop: 10,
    marginLeft: 0,
    fontSize: 10,
    color: 'gray',
  },
  repair: {
    flexDirection: 'row',
    marginTop: -75,
    paddingLeft: 265,
    justifyContent: 'space-between',
  },
  hScreenText: {
    fontSize: 25,
    fontWeight: '600',
    justifyContent: 'center',
  },
  free: {
    width: 60,
    height: 60,
  },
  textBuy: {
    paddingTop: 40,
    marginLeft: -140,
    fontSize: 10,
    color: 'gray',
  },
  freelance: {
    flexDirection: 'row',
    marginTop: -55,
    paddingLeft: 285,
    justifyContent: 'space-between',
  },
  image: {
    width: '100%',
    height: 105,
    borderRadius: 10,
    marginTop: -20,
  },
  safeStyle: {
    justifyContent: 'space-between',
    margin: 10,
    flexDirection: 'row',
  },
  text: {
    justifyContent: 'space-between',
    marginTop: -10,
    flexDirection: 'row',
  },
  hViewStyle: {
    justifyContent: 'center',
    width: '31%',
  },
  rectangle: {
    marginTop: -20,
    paddingLeft: 6,
  },
  recImage: {
    borderRadius: 5,
    height: 3,
    width: 30,
  },
  textStyle: {
    fontSize: 22,
    fontWeight: '600',
    width: '57%',
    marginTop: 72,
    paddingLeft: 20,
  },
  textView: {
    justifyContent: 'space-between',
  },
  customBtnBG: {
    marginLeft: 350,
    marginTop: -35,
  },
  gitimage: {
    width: 199.77,
    height: 29.55,
  },
  notification: {
    width: 40,
    height: 45,
    paddingTop: 10,
  },
  notificationview: {
    paddingLeft: 78,
  },
  header: {
    paddingTop: 15,
    paddingLeft: 13,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  registerStyle: {
    margin: 10,
    width: '14%',
    height: 32,
  },
  earnStyle: {
    margin: 10,
    width: '8%',
    height: 30,
  },
  preferencStyle: {
    margin: 10,
    width: '10%',
    height: 32,
  },
  gitCoins: {
    margin: 10,
    width: '9%',
    height: 32,
  },
  inputStyle: {
    width: 22,
    height: 20,
    marginTop: 10,
  },
  locationview: {
    paddingLeft: 10,
    marginTop: -17,
  },
  locText: {
    paddingLeft: 65,
    marginTop: -17,
  },
  radiusview: {
    paddingLeft: 300,
    marginTop: -20,
  },
  homeStyle: {
    fontWeight: '600',
    paddingLeft: 20,
  },
  numberText: {
    paddingLeft: 315,
    marginTop: -18,
    fontSize: 14,
    color: 'gray',
  },
});
